name = "Ponydevs - Something for Everyone"
description = "Ponydevs modpack"
author = "Queen Izzy"
version = "1.3.1"
minecraft_version = "1.20.1"
mod_loader.id = "fabric"
mod_loader.version = "0.14.22"

[mods.modrinth]
fabric-api = {project_id = "P7dR8mSH", version_id = "tFw0iWAk"} # Fabric API 0.90.0+1.20.1 - https://modrinth.com/mod/fabric-api
sodium = {project_id = "AANobbMI", version_id = "4OZL6q9h"} # Sodium mc1.20.1-0.5.3 - https://modrinth.com/mod/sodium
iris = {project_id = "YL57xq9U", version_id = "DsjYuGMO"} # Iris Shaders 1.6.10+1.20.1 - https://modrinth.com/mod/iris
lithium = {project_id = "gvQqBUqZ", version_id = "ZSNsJrPI"} # Lithium mc1.20.1-0.11.2 - https://modrinth.com/mod/lithium
modmenu = {project_id = "mOgUt4GM", version_id = "lEkperf6"} # Mod Menu 7.2.2 - https://modrinth.com/mod/modmenu
indium = {project_id = "Orvt0mRa", version_id = "Lue6O9z9"} # Indium 1.0.27+mc1.20.1 - https://modrinth.com/mod/indium
entityculling = {project_id = "NNAgCjsB", version_id = "BDwHAdWc"} # Entity Culling 1.6.2-1.20.2 - https://modrinth.com/mod/entityculling
ferrite-core = {project_id = "uXXizFIs", version_id = "FCnCG6PS"} # FerriteCore 6.0.0-fabric - https://modrinth.com/mod/ferrite-core
betterf3 = {project_id = "8shC1gFX", version_id = "FtJ0KSLo"} # BetterF3 7.0.1 - https://modrinth.com/mod/betterf3
bluemap = {project_id = "swbUV1cr", version_id = "xgcQSkBc"} # BlueMap 3.17-fabric-1.20 - https://modrinth.com/mod/bluemap
dynamic-fps = {project_id = "LQ3K71Q1", version_id = "MJxmQ042"} # Dynamic FPS 3.2.1 - https://modrinth.com/mod/dynamic-fps
lambdynamiclights = {project_id = "yBW8D80W", version_id = "mYl4RvKg"} # LambDynamicLights 2.3.2+1.20.1 - https://modrinth.com/mod/lambdynamiclights
farmers-delight-fabric = {project_id = "4EakbH8e", version_id = "rlm3hWGx"} # Farmer's Delight [Fabric] 1.4.2 - https://modrinth.com/mod/farmers-delight-fabric
resourceful-lib = {project_id = "G1hIVOrD", version_id = "xeUwwWis"} # Resourceful Lib 2.1.11 - https://modrinth.com/mod/resourceful-lib
resourceful-config = {project_id = "M1953qlQ", version_id = "nVDWZ9N7"} # Resourceful Config 2.1.0 - https://modrinth.com/mod/resourceful-config
botarium = {project_id = "2u6LRnMa", version_id = "YgOh7n9M"} # Botarium 2.2.0 - https://modrinth.com/mod/botarium
ad-astra = {project_id = "3ufwT9JF", version_id = "DruFc2hK"} # Ad Astra 1.15.4 - https://modrinth.com/mod/ad-astra
cloth-config = {project_id = "9s6osm5g", version_id = "s7VTKfLA"} # Cloth Config API 11.1.106+fabric - https://modrinth.com/mod/cloth-config
promenade = {project_id = "GuE5FpvB", version_id = "A5YD9uS3"} # Promenade v4.1.1 - https://modrinth.com/mod/promenade
wwoo = {project_id = "II7t6llZ", version_id = "cNiETBJi"} # William Wythers' Overhauled Overworld 2.0.0 - https://modrinth.com/mod/wwoo
ct-overhaul-village = {project_id = "fgmhI8kH", version_id = "7LYJgioY"} # ChoiceTheorem's Overhauled Village 3.3.5 - https://modrinth.com/mod/ct-overhaul-village
ctov-farmers-delight-compat = {project_id = "CdRC4fyI", version_id = "Bp3TnFpM"} # CTOV - Farmer Delight Compat 2.0+mod - https://modrinth.com/mod/ctov-farmers-delight-compat
beautify-refabricated = {project_id = "DhSSvaxs", version_id = "Dwqjxrdn"} # Beautify: Refabricated 1.0.0+1.20 - https://modrinth.com/mod/beautify-refabricated
ctov-beautify-compat = {project_id = "iunZDj0l", version_id = "elBmQR7P"} # CTOV - Beautify Compat 2.0+mod - https://modrinth.com/mod/ctov-beautify-compat
better-combat = {project_id = "5sy6g3kz", version_id = "Z6wHaEla"} # Better Combat 1.7.4+1.20.1-fabric - https://modrinth.com/mod/better-combat
sleep-tight = {project_id = "tNai0h2Y", version_id = "cBS0eOt9"} # Sleep Tight 1.20-1.1.6 - https://modrinth.com/mod/sleep-tight
create-fabric = {project_id = "Xbc0uyRg", version_id = "qlA1WuOK"} # Create Fabric 0.5.1-d-build.1161+mc1.20.1 - https://modrinth.com/mod/create-fabric
create-steam-n-rails = {project_id = "ZzjhlDgM", version_id = "vVIvVuGn"} # Create: Steam 'n' Rails 1.5.1-fabric-mc1.20.1 - https://modrinth.com/mod/create-steam-n-rails
slice-and-dice = {project_id = "GmjmRQ0A", version_id = "etRuKHcg"} # Create Slice & Dice 3.0.0 - https://modrinth.com/mod/slice-and-dice
xaeros-minimap = {project_id = "1bokaNcj", version_id = "iztrg4XH"} # Xaero's Minimap 23.8.2_Fabric_1.20 - https://modrinth.com/mod/xaeros-minimap
emi = {project_id = "fRiHVvU7", version_id = "IOqjd65y"} # EMI 1.0.22+1.20.1+fabric - https://modrinth.com/mod/emi
extra-mod-integrations = {project_id = "bpRHnWUb", version_id = "juXS5CaW"} # EMI Addon: Extra Mod Integrations 0.4.1+1.20.1 - https://modrinth.com/mod/extra-mod-integrations
playeranimator = {project_id = "gedNE4y2", version_id = "yDqYTUaf"} # playerAnimator 1.0.2-rc1+1.20-fabric - https://modrinth.com/mod/playeranimator
fabric-language-kotlin = {project_id = "Ha28R6CL", version_id = "48ri5y9r"} # Fabric Language Kotlin 1.10.10+kotlin.1.9.10 - https://modrinth.com/mod/fabric-language-kotlin
trinkets = {project_id = "5aaWibi9", version_id = "e563ycts"} # Trinkets 3.7.1 - https://modrinth.com/mod/trinkets
dawn = {project_id = "meZK2DCX", version_id = "J6b05anw"} # Dawn API v5.0.0 - https://modrinth.com/mod/dawn
cristel-lib = {project_id = "cl223EMc", version_id = "k0RzoTGC"} # Cristel Lib 1.1.3-fabric - https://modrinth.com/mod/cristel-lib
moonlight = {project_id = "twkfQtEc", version_id = "BsdtnGcc"} # Moonlight Lib fabric_1.20-2.8.48 - https://modrinth.com/mod/moonlight
patchouli = {project_id = "nU0bVIaL", version_id = "tzz6fEoj"} # Patchouli 1.20.1-81-fabric - https://modrinth.com/mod/patchouli
travelersbackpack = {project_id = "rlloIFEV", version_id = "xoAo10oT"} # Traveler's Backpack 1.20.1-9.1.6 - https://modrinth.com/mod/travelersbackpack
cardinal-components-api = {project_id = "K01OU20C", version_id = "qW85eawp"} # Cardinal Components API 5.2.2 - https://modrinth.com/mod/cardinal-components-api
cc-tweaked = {project_id = "gu7yAYhd", version_id = "s6Ov3R0y"} # CC: Tweaked 1.108.1 - https://modrinth.com/mod/cc-tweaked
cccbridge = {project_id = "fXt291FO", version_id = "57pJUQQM"} # CC:C Bridge 1.6.2b-fabric - https://modrinth.com/mod/cccbridge
continuity = {project_id = "1IjD5062", version_id = "Z9FJWLMt"} # Continuity 3.0.0-beta.4+1.20.1 - https://modrinth.com/mod/continuity
entitytexturefeatures = {project_id = "BVzZfTc1", version_id = "UPenaMj3"} # [ETF] Entity Texture Features 4.5.1 - https://modrinth.com/mod/entitytexturefeatures
tidal-towns = {project_id = "EEIwvQVo", version_id = "9rGNfR18"} # Tidal Towns 1.2+mod - https://modrinth.com/mod/tidal-towns
origins = {project_id = "3BeIrqZR", version_id = "OdNHB7Bh"} # Origins 1.10.0 - https://modrinth.com/mod/origins
bobby = {project_id = "M08ruV16", version_id = "2cuVyTav"} # Bobby 5.0.1 - https://modrinth.com/mod/bobby
chunks-fade-in = {project_id = "JaNmzvA8", version_id = "XddlRahr"} # Chunks fade in v1.0.4-1.20.1 - https://modrinth.com/mod/chunks-fade-in
mine-little-pony = {project_id = "JBjInUXM", version_id = "sMXaqaZU"} # Mine Little Pony 4.10.2+1.20 - https://modrinth.com/mod/mine-little-pony
ponyorigins = {project_id = "TwZGSxgV", version_id = "D5gE4nPp"} # Pony Origins 1.1.0-b1 - https://modrinth.com/mod/ponyorigins
soundsbegone = {project_id = "FOIvwGKz", version_id = "u6jZvhPV"} # Sounds Be Gone! 1.1.2 - https://modrinth.com/mod/soundsbegone
sound-physics-remastered = {project_id = "qyVF9oeo", version_id = "67Uq017p"} # Sound Physics Remastered fabric-1.20.1-1.2.1 - https://modrinth.com/mod/sound-physics-remastered
simple-voice-chat = {project_id = "9eGKb6K1", version_id = "f1enbAVD"} # Simple Voice Chat fabric-1.20.1-2.4.26 - https://modrinth.com/mod/simple-voice-chat
audioplayer = {project_id = "SRlzjEBS", version_id = "dyAoCTEw"} # AudioPlayer fabric-1.20.1-1.8.1 - https://modrinth.com/mod/audioplayer
jade = {project_id = "nvQzSEkH", version_id = "ckXpheui"} # Jade 🔍 11.6.2 - https://modrinth.com/mod/jade
jade-addons-fabric = {project_id = "fThnVRli", version_id = "GYWtjmY7"} # Jade Addons (Fabric) 5.2.1 - https://modrinth.com/mod/jade-addons-fabric
jei = {project_id = "u6dRKJwZ", version_id = "lIRFslED"} # Just Enough Items 15.2.0.27 - https://modrinth.com/mod/jei
just-enough-resources-jer = {project_id = "uEfK2CXF", version_id = "ecxqA4B1"} # Just Enough Resources (JER) 1.4.0.238 - https://modrinth.com/mod/just-enough-resources-jer

# Farmer's Respire (Fabric) 2.3.4 - https://www.curseforge.com/minecraft/mc-mods/farmers-respite-fabric
# [mods.curseforge.farmers-respite-fabric]
# project_id = 811003
# version_id = 4754429
# ignored_deps = [
    # Farmer's Delight (Fabric) is included from Modrinth
#     {project_id = 482834},
    # Fabric API is included from Modrinth
#    {project_id = 306612}
# ]
