
name: Build Release

permissions:
    contents: write

on:
    push:
        tags:
            - 'v*.*.*'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            NF_REVISION: '6adae37e77b9596cbd9e1f90277a26e6fb4cc4c7'
            ARTIFACT_NAME: ${{ (github.event_name == 'push') && github.ref_name || format('{0}-{1}', github.actor, github.sha) }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                    toolchain: stable
                    profile: minimal
            - name: Install Netherfire
              uses: baptiste0928/cargo-install@v2
              with:
                    crate: netherfire
                    git: https://github.com/octylFractal/netherfire.git
                    rev: ${{ env.NF_REVISION }}
            - name: Run Netherfire
              run: netherfire --create-modrinth-pack client --create-server-base server ./
            - name: Archive Server Files
              uses: ksm2/archive-action@v1
              with:
                    name: server-ponydev-sfe-${{ env.ARTIFACT_NAME }}
                    include: server/**/*
                    format: tar
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                    name: ${{ env.ARTIFACT_NAME }}
                    path: |
                        client/*.mrpack
                        server-ponydev-sfe-${{ env.ARTIFACT_NAME }}.*
            - name: Extract release notes
              id: extract-release-notes
              uses: ffurrer2/extract-release-notes@v1
            - name: Release
              uses: softprops/action-gh-release@v1
              if: github.event_name == 'push'
              with:
                    files: |
                        client/*.mrpack
                        server-ponydev-sfe-${{ github.ref_name }}.*
                    tag_name: ${{ github.ref_name }}
                    body: ${{ steps.extract-release-notes.outputs.release_notes }}
                    draft: false
                    prerelease: false
