
name: Build Release

on:
    push:
        tags:
            - 'v*.*.*'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            NF_REVISION: 'f3ce9858c05adef8e533b106359cddb6a7f6f355'
            IS_PUSH: ${{ github.event_name == 'push' }}
            ARTIFACT_NAME: ${{ (github.event_name == 'push') && github.ref_name || format('{0}-{1}', github.actor, github.sha) }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                    toolchain: stable
                    profile: minimal
            - name: Install Netherfire
              uses: taiki-e/cache-cargo-install-action@v1
              with:
                    tool: netherfire
                    git: https://github.com/octylFractal/netherfire.git
                    rev: ${{ env.NF_REVISION }}
            - name: Run Netherfire
              run: netherfire --create-modrinth-pack client --create-server-base server ./
            - name: Zip Server Files
              uses: vimtor/action-zip@v1
              with:
                    files: server/**/*
                    dest: server-ponydev-sfe-${{ env.ARTIFACT_NAME }}
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                    name: ${{ env.ARTIFACT_NAME }}
                    path: |
                        client/*.mrpack
                        server-ponydev-sfe-${{ env.ARTIFACT_NAME }}.zip
            - name: Release
              uses: softprops/action-gh-release@v1
              if: env.IS_PUSH
              with:
                    files: |
                        client/*.mrpack
                        server-ponydev-sfe-${{ github.ref_name }}.zip
                    tag_name: ${{ github.ref_name }}
                    body: ${{ github.ref_name }}
                    draft: false
                    prerelease: false
